#### Introduction to Numpy

In [1]:
# Load the numpy library
import numpy as np

In [2]:
# Check the version
np.__version__

'1.16.4'

In [4]:
# Create a list of 10 numbers
create_list = list(range(10))
create_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
print("Items in the list: ", create_list)

Items in the list:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [5]:
# Function to print datatypes of list
def print_dtypes(l):
    for item in l:
        print(type(item))

In [6]:
# Check the datatypes of the list
print_dtypes(create_list)

<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>
<class 'int'>


In [7]:
# Let's try to create list with different datatypes
list_hetrogeneous = [1, "2", "A", 3, {"A" :3, "B":4}, 9, (10, 20, 30, 40), True]  #it has boolean valus,dict,string,integer,tuple ,thats why it is called heterozeneous list

In [8]:
# Print hetrogeneous list
print("Heterogeneous List:\n", list_hetrogeneous)

Heterogeneous List:
 [1, '2', 'A', 3, {'A': 3, 'B': 4}, 9, (10, 20, 30, 40), True]


In [9]:
# Check the Datatypes in the hetrogeneous list
print_dtypes(list_hetrogeneous)

<class 'int'>
<class 'str'>
<class 'str'>
<class 'int'>
<class 'dict'>
<class 'int'>
<class 'tuple'>
<class 'bool'>


#### Creating Numpy arrays

Unlike lists, numpy arrays are homogeneous in nature that means they comprise of only one data type like integer/ float/ double/ string/ boolean etc...

In [ ]:
# Let's try to create numpy array with different datatypes
np.array([[1, 2, 3],
         ["A", "B", "C"]])

array([['1', '2', '3'],
       ['A', 'B', 'C']],
      dtype='<U21')

As you can see above numpy converted integers to strings to make array homogeneous

Let's try to create some numpy arrays

In [12]:
# creating array with 5 one's of type int
print(np.ones(5, dtype='int'))
print(np.zeros(6,dtype="int"))

[1 1 1 1 1]
[0 0 0 0 0 0]


In [14]:
# creating array with 5 zero's of type float
np.zeros(5, dtype='float')
print(np.zeros(4))

[0. 0. 0. 0.]


In [13]:
#Lets create an identity matrix of 2x2
np.eye(2)

array([[1., 0.],
       [0., 1.]])

Understanding the importance of np.random.seed()

In [36]:
# create a 5x5 array with elements taken from normal distribution of mean 0 and standard deviation 1 
# Setting random.seed()
np.random.seed(10)
x = np.random.normal(0, 1, (5,5))
x

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597],
       [-0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125]])

In [31]:
# create a 5x5 array with elements taken from normal distribution of mean 0 and standard deviation 1 
x = np.random.normal(0, 1, (5,5))
x

array([[-0.84090138,  1.0055851 , -1.02380418,  0.18177391, -0.41668095],
       [ 1.97840875,  1.91744468, -1.031007  , -0.48331191, -0.64508015],
       [ 0.06034816,  0.54793044,  0.84514847, -1.20718132,  0.37484034],
       [ 0.94234783, -0.35126393,  0.45973503, -0.04851666,  0.41548191],
       [-0.70187614,  0.18546447,  0.46834978,  0.03952335,  0.71614054]])

As you can see x contains different values than we created above since we did not set seed value.
With different seed value numpy generates different numbers.

In [37]:
# create a 5x5 array with elements taken from normal distribution of mean 0 and standard deviation 1 
np.random.seed(20)
x = np.random.normal(0, 1, (5,5))
x

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191, -1.08483259],
       [ 0.55969629,  0.93946935, -0.97848104,  0.50309684,  0.40641447],
       [ 0.32346101, -0.49341088, -0.79201679, -0.84236793, -1.27950266],
       [ 0.24571517, -0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821, -0.24333877]])

Set the same seed value if you want to generate same random numbers. 
Let's try with seed=10.

In [38]:
# create a 5x5 array with elements taken from normal distribution of mean 0 and standard deviation 1 
np.random.seed(10)
x = np.random.normal(0, 1, (5,5))
x

array([[ 1.3315865 ,  0.71527897, -1.54540029, -0.00838385,  0.62133597],
       [-0.72008556,  0.26551159,  0.10854853,  0.00429143, -0.17460021],
       [ 0.43302619,  1.20303737, -0.96506567,  1.02827408,  0.22863013],
       [ 0.44513761, -1.13660221,  0.13513688,  1.484537  , -1.07980489],
       [-1.97772828, -1.7433723 ,  0.26607016,  2.38496733,  1.12369125]])

seed = 20

In [39]:
# create a 5x5 array with elements taken from normal distribution of mean 0 and standard deviation 1 
np.random.seed(20)
x = np.random.normal(0, 1, (5,5))
x

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191, -1.08483259],
       [ 0.55969629,  0.93946935, -0.97848104,  0.50309684,  0.40641447],
       [ 0.32346101, -0.49341088, -0.79201679, -0.84236793, -1.27950266],
       [ 0.24571517, -0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821, -0.24333877]])

In [40]:
# Check the shapes of created numpy arrays
print("Shape of x is:", x.shape)

Shape of x is: (5, 5)


#### Array Indexing 

Indexing in python starts from 0.

In [41]:
# Let's create 1-D array with alphabets
x = np.array(["A", "B", "C", "D", "E", "F", "G"])

In [42]:
# Get value of first element
x[0]

'A'

In [43]:
# Get value at second element
x[1]

'B'

In [44]:
# Get value of first element from last 
x[-1]

'G'

In [45]:
# Get value of second element from last 
x[-2]

'F'

In [46]:
# Let's create 2-D array
np.random.seed(10)
y = np.random.normal(0, 1, (2,2))
y

array([[ 1.3315865 ,  0.71527897],
       [-1.54540029, -0.00838385]])

In [47]:
# Get value of 1st row and 1st column
y[0, 0]

1.331586504129518

In [48]:
# Get value of last row and last column
y[-1, -1]

-0.008383849928522256

#### Array Slicing 

Access multiple elements of the array 

In [49]:
# Create 1-D array of 20 elements from 10-30
x = np.arange(10, 30)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [50]:
# Access elements till 4th position
x[ : 5]

array([10, 11, 12, 13, 14])

In [51]:
# Access elements from 10th position
x[10 : ]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [60]:
# Access elements from 14th to 19th position
x[14 : 19]
print(x[-1])

29


In [55]:
# Reverse the array
print(x)
x[::-1]

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]


array([29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13,
       12, 11, 10])

#### Array Concatenation

Array Concatenation = Combining 2 or more arrays, that's it.

In [58]:
# You can concatenate two or more arrays at once.

arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])
arr_3 = np.array(['A','B', 'C'])

print(np.concatenate([arr_1, arr_2, arr_3]))

arr_4=np.array(["paul","xerexes","das"])
arr_5=np.array(["lonely","solo"])
arr_6=np.concatenate([arr_4,arr_5])
print(arr_6)


['1' '2' '3' '4' '5' '6' 'A' 'B' 'C']
['paul' 'xerexes' 'das' 'lonely' 'solo']


In [59]:
# You can also use this function to create 2-dimensional arrays.

matrix = np.array([["I", "Love", "ML"],["not", "you", "girl"]])
print(matrix)
np.concatenate([matrix, matrix])

[['I' 'Love' 'ML']
 ['not' 'you' 'girl']]


array([['I', 'Love', 'ML'],
       ['not', 'you', 'girl'],
       ['I', 'Love', 'ML'],
       ['not', 'you', 'girl']], dtype='<U4')

In [62]:
# Using its axis parameter, you can define row-wise or column-wise matrix.

# Example showing concatinating two 2-d arrays one below the other.

concatenated_matrix_axis_0 = np.concatenate([matrix, matrix],axis=0)

print(concatenated_matrix_axis_0)

print (" size of concatenated_matrix_axis_0 = ", concatenated_matrix_axis_0.shape)  #4 rows and 3 columns


[['I' 'Love' 'ML']
 ['not' 'you' 'girl']
 ['I' 'Love' 'ML']
 ['not' 'you' 'girl']]
 size of concatenated_matrix_axis_0 =  (4, 3)


In [63]:
# Example showing concatinating two 2-d arrays one after/adjacent the other

concatenated_matrix_axis_1 = np.concatenate([matrix, matrix],axis=1)

print(concatenated_matrix_axis_1)

print ("size of concatenated_matrix_axis_1 =", concatenated_matrix_axis_1.shape)

[['I' 'Love' 'ML' 'I' 'Love' 'ML']
 ['not' 'you' 'girl' 'not' 'you' 'girl']]
size of concatenated_matrix_axis_1 = (2, 6)


Until now, we used the concatenation function of arrays of equal dimension. 

How can we combine a 1-D array and 2-D array.

np.vstack or np.hstack help us in such situations. 

Let us see how.

In [66]:
# Stack using vstack

x = np.array([9, 10, 11])
matrix = np.array([[12, 13, 14],[15, 16, 17]])
print(x)
print(matrix)
vstack_example = np.vstack([x, matrix])

print(vstack_example)
print("Shape of stacked array:", vstack_example.shape)

[ 9 10 11]
[[12 13 14]
 [15 16 17]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
Shape of stacked array: (3, 3)


In [68]:
# Stack using hstack

z = np.array([[0], [0]])
print(z)
print(matrix)
hstack_example = np.hstack([matrix, z])

print(hstack_example)
print("Shape of stacked array:", hstack_example.shape)

[[0]
 [0]]
[[12 13 14]
 [15 16 17]]
[[12 13 14  0]
 [15 16 17  0]]
Shape of stacked array: (2, 4)


Excercise: 

    1) Create a 1-D array and split them into three 1-D arrays.
    2) Create a 2-D array of size 10x10 and split them into two 2-D arrays.

Hint: Explore np.split() and np.vsplit()

In [73]:
a=np.array([1,2,3])
print(a)
np.split(a,3)

[1 2 3]


[array([1]), array([2]), array([3])]

In [77]:
c=np.random.normal(0,1,(10,10))
print(c)
d=np.vsplit(c,2)
print(d)

[[-0.47140008  0.34947641  1.61145729  0.23933927  0.48500263 -1.65860471
   2.67991031 -1.10352213  1.81778261 -0.55604734]
 [ 0.95771124  0.81522068  0.0643194  -0.16640537 -0.94070977 -0.0535945
   1.1011362   0.37212255 -0.88346099  1.15805157]
 [-1.20365349  0.20983914 -0.89118692 -0.78268775  1.07973068 -0.46284089
  -1.51507568 -0.53871853  0.75662186 -0.72939922]
 [ 1.21478265  1.00828297  0.07328301  1.17373241  1.86295167 -1.9836365
   1.15668893  0.60928227 -0.32320123  0.66414561]
 [ 0.39672599 -0.57611686  1.48821839  0.14024687  1.18831675 -0.24574539
  -1.63558662  0.24479809 -0.23508223 -1.26082781]
 [-1.69196793  0.61645092  1.26969128  1.39733798  0.53422496  0.00410204
   0.18941984  0.04477469  0.79468527 -0.49314074]
 [-1.26158974 -0.21926026  0.19727222 -0.25528045  0.02580759  2.20096644
   0.8843676  -1.38682253  0.65366231 -2.17660863]
 [ 0.61894892  0.4772343   0.02609653 -0.96970567 -0.98372812  0.41253272
  -0.61430485  0.83708178 -0.62361901 -0.3631862 ]
 [